### PR TITLE
Implement ts-migrate-server using @ts-morph/bootstrap

### PR DESCRIPTION
**Pull request by edsrzf**
I propose that ts-migrate replace most of the implementation of the `ts-migrate-server` package with [`@ts-morph/bootstrap`](https://github.com/dsherret/ts-morph/tree/latest/packages/bootstrap). I have not yet updated any documentation, but all tests pass and I've had success running against real projects. Also note that some types have changed slightly.

`@ts-morph/bootstrap` is a library for quickly getting setup with TypeScript's compiler APIs and provides functionality similar to what you can get through communicating with the TypeScript language server. It is built on top of `@ts-morph/common`, which also powers the main `ts-morph` package, used to analyze and manipulate TypeScript code.

Pros:
* Less code for this project to maintain.
* Easier access to things like `LanguageService` and `TypeChecker` to enable plugins to do things like renaming, using TypeScript's built-in codefixes, or performing type-based transformations.
* Plugins that rely on diagnostics are significantly faster. (See results below.)
* Simpler execution model. No forking or interprocess communication required.

Cons:
* Another dependency, with all the downsides that entails.
* You could argue that the TypeScript server, being a core part of TypeScript, has a better chance of being correct and reliable due to its wide usage and its support from Microsoft. The ts-morph project is maintained mainly by a single author with no sponsor. However, it has consistently been worked on for over 3 years, is reasonably well-documented, and appears to be built to a high standard.

## Performance

I ran the `explicit-any` plugin, which relies on diagnostics, across a code base consisting of 123 TypeScript files and 5822 SLOC, using both the master branch (version 0.1.6) and this branch. Each branch ran 3 times.

Timings for master branch (version 0.1.6), low to high:
```
6153.421ms
6199.109ms
6343.678ms
```

Timings for this branch, low to high:
```
4496.154ms
4505.080ms
4521.402ms
```

This branch is about 38% faster.

## Open Questions

* What would this mean for the `ts-migrate-server` package? The name wouldn't really make sense anymore, but it does seem useful to have a package that defines plugin interfaces and a `migrate` function.
* Do plugins still need to be allowed to be async since `getDiagnostics` is no longer async? What's the case for it?
* What's the best way to expose language service functionality to plugins? Do we even need `getDiagnostics` anymore? It might be more useful to supply a `getLanguageService`, although this could make testing more difficult.

### CODE REVIEW

**Comment by Rudeg** [comment]
Hey @edsrzf, thanks for the proposal!

Props and cons look good to me, and performance gains seem to be excellent.

> What would this mean for the ts-migrate-server package? The name wouldn't make sense anymore, but it does seem useful to have a package that defines plugin interfaces and a migrate function.

If we're moving forward with `ts-morph`, I would think about renaming it to something like `ts-migrate-runner` or similar. I would keep the migrate function and plugin interfaces as a separate package.

> Do plugins still need to be allowed to be async since getDaiagnostics is no longer async? What's the case for it?

The main reason for this was `getDiagnostics`, I don't remember any additional use cases. 

>What's the best way to expose language service functionality to plugins? Do we even need getDiagnostics anymore? It might be more useful to supply a getLanguageService, although this could make testing more difficult.

`getLanguageService` seems like a more flexible way and would potentially allow more things in the future. But it will make testing more complex, indeed. 

Overall, I'm leaning towards moving forward with this implementation. 

@brieb @lencioni wdyt?

**Comment by brieb** [comment]
Wow, thank you for the contribution! Always love to see red diffs. 👍 

Faster and less code to maintain? Sounds like a win to me. Had some questions before moving forward.

Does `@ts-morph/bootstrap` keep up quickly with new TypeScript versions? What has the historical lag time been between when a new TypeScript version is released and when `@ts-morph/bootstrap` is updated?

Are there any TypeScript library APIs we'd lose access to by going through `@ts-morph/bootstrap` instead?

**Comment by edsrzf** [comment]
Sorry for the slow response. I've been on vacation.

> Does @ts-morph/bootstrap keep up quickly with new TypeScript versions? What has the historical lag time been between when a new TypeScript version is released and when @ts-morph/bootstrap is updated?

Good question!

| TypeScript Version  | TypeScript Release Date | `@ts-morph/bootstrap` Version | `@ts-morph/bootstrap` Release Date | Lag Time |
| - | - | - | - | - |
| 4.0 | August 20, 2020 | 0.6.0 | August 21, 2020 | 1 day |
| 3.9 | May 12, 2020 | 0.5.0 | May 17, 2020 | 5 days |
| 3.8 | February 20, 2020 | 0.4.0 | February 24, 2020 | 4 days |

The package doesn't go back much further than that, but the main package, `ts-morph`, looks like it follows the pattern of lagging behind TypeScript releases by only a few days in most cases.

> Are there any TypeScript library APIs we'd lose access to by going through `@ts-morph/bootstrap` instead?

I don't believe so, but I haven't exhaustively checked. As far as I can tell it provides basically the same APIs, just accessible in a more direct way.

**Comment by Rudeg** [comment]
> it follows the pattern of lagging behind TypeScript releases by only a few days in most cases

Thanks for looking into this. The results seem reasonable to me, and the lag is not that big.

Overall, I'm in favor of switching to the `@ts-morph/bootstrap`.

**Comment by edsrzf** [comment]
Getting back around to looking at this. So to make this mergeable, would it be enough to resolve the conflict with the master branch and update the docs?

I know there are a few other things we might want to do as followup, but I wonder if it's necessary to do them all in one pull request. In rough priority order:

* Rename `ts-migrate-server` to `ts-migrate-runner`
* Look at removing `getDiagnostics` in favor of `getLanguageService`
* Remove support for async plugins, unless there's a good reason not to

**Comment by Rudeg** [comment]
@edsrzf Yes, that’s sound correct to me!
Thanks for working on this one :)

**Review by Rudeg — APPROVED** [review]
🎉 🎉 🎉

**Comment by Rudeg** [comment]
@edsrzf Published as `0.1.9` 🎉

**Pull request merged**
